version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: PeruvianWishes
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    container_name: app
    build: .
    env_file:
      - ./.env
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy
    command: npm run dev
    volumes:
      - ./src:/app/src